name: 'Test OCI Image'
description: 'Tests OCI image using make oci_test.'
inputs:
  arch:
    description: 'Target architecture (amd64 or arm64)'
    required: true
  distro:
    description: 'Target distribution (e.g., bookworm, trixie)'
    required: false
  ocipgversion:
    description: 'PostgreSQL version (e.g., pg18)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Build OCI image for ${{ inputs.arch }}
      run: |
        export DISTRO="${{ inputs.distro || 'bookworm' }}"
        export OCIPGVERSION="${{ inputs.ocipgversion }}"
        export PG_VERSION_OCI="${OCIPGVERSION#pg}"
        if [ "${{ inputs.arch }}" = "amd64" ]; then
          make oci_test_cleanup
        elif [ "${{ inputs.arch }}" = "arm64" ]; then
          make oci_test_cleanup
        else
          echo "Unsupported arch: ${{ inputs.arch }}" && exit 1
        fi
      shell: bash
