name: 'Delete GitHub Release'
description: 'Deletes a GitHub release for a given tag if it exists.'

inputs:
  github_token:
    description: 'GitHub token with repo access'
    required: true
  release_tag:
    description: 'Tag name of the release to delete'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install gh CLI
      run: |
        if ! command -v gh &> /dev/null; then
          echo "Installing GitHub CLI..."
          sudo apt-get update && sudo apt-get install -y gh
        fi
      shell: bash

    - name: Delete GitHub release for tag
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        RELEASE_TAG: ${{ inputs.release_tag }}
      run: |
        echo "Looking for release with tag: $RELEASE_TAG"
        RELEASE_ID=$(gh api repos/${{ github.repository }}/releases --jq ".[] | select(.tag_name==\"$RELEASE_TAG\") | .id")
        if [ -n "$RELEASE_ID" ]; then
          echo "Deleting release with ID $RELEASE_ID for tag $RELEASE_TAG"
          gh api --method DELETE repos/${{ github.repository }}/releases/$RELEASE_ID
        else
          echo "No release found for tag $RELEASE_TAG"
        fi
      shell: bash
