site_name: pglinter
site_description: PostgreSQL Database Linting and Analysis Extension
site_author: pglinter contributors
copyright: Copyright 2024-2025 pglinter contributors
repo_url: https://github.com/pmpetit/pglinter
edit_uri: edit/main/docs/

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - sql
    - bash
    - rust

nav:
  - 'Home': index.md
  - 'Configuration': configure.md
  - 'Security': SECURITY.md
  - How-To Guides:
    - 'Overview': how-to/README.md
  - Functions Reference:
    - 'Functions': functions/README.md
  - Rules Reference:
    - 'Rules': rules/README.md
  - Examples:
    - 'Usage Examples': examples/README.md
    - 'Rules management': examples/rule_level_management.md
  - Development:
    - 'Contributing': dev/README.md

# Markdown settings
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - tables
  - fenced_code

# Additional settings
use_directory_urls: true
strict: false

# Plugin settings
plugins:
  - search

# Extra settings for ReadTheDocs
extra:
  version:
    provider: mike
