# .github/actions/reusable-package-action/action.yml
name: 'Build package and upload'

description: 'Builds rpm/deb package and upload.'

inputs:
  pgver:
    description: 'The PostgreSQL major version with the "pg" prefix (e.g. `pg13`, `pg16`, etc.)'
    required: true
  tag:
    description: "The tag version"
    required: true
  arch:
    description: 'Target architecture (amd64 or arm64)'
    required: false
    default: 'amd64'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup workspace for postgres user
      run: |
        chown -R postgres:postgres $GITHUB_WORKSPACE
        chmod -R 755 $GITHUB_WORKSPACE
      shell: bash

    - name: Extract version from Cargo.toml
      id: get-version
      run: |
        VERSION=$(grep '^version = ' Cargo.toml | awk -F'"' '{print $2}')
        echo "Extracted version: $VERSION"
        echo "PGLINTER_MINOR_VERSION=$VERSION" >> $GITHUB_ENV
        echo "PACKAGE_ARCH=${{ inputs.arch }}" >> $GITHUB_ENV
      shell: bash

    - name: Build packages
      run: |
        export PACKAGE_ARCH=${{ inputs.arch }}
        su - postgres -c "cd $GITHUB_WORKSPACE && PGVER=${{ inputs.pgver }} PACKAGE_ARCH=${{ inputs.arch }} make deb"
        su - postgres -c "cd $GITHUB_WORKSPACE && PGVER=${{ inputs.pgver }} PACKAGE_ARCH=${{ inputs.arch }} make rpm"
      shell: bash

    - name: 'RPM package for ${{ inputs.pgver }} (${{ inputs.arch }})'
      uses: actions/upload-artifact@v4
      with:
        name: pglinter-${{ inputs.pgver }}-${{ env.PGLINTER_MINOR_VERSION }}-${{ inputs.arch }}.rpm
        path: target/release/pglinter-${{ inputs.pgver }}/*.rpm

    - name: 'DEB package for ${{ inputs.pgver }} (${{ inputs.arch }})'
      uses: actions/upload-artifact@v4
      with:
        name: pglinter-${{ inputs.pgver }}-${{ env.PGLINTER_MINOR_VERSION }}-${{ inputs.arch }}.deb
        path: target/release/pglinter-${{ inputs.pgver }}/*.deb
