name: 'Build OCI Image (Clean)'
description: 'CLean OCI image.'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: 'composite'
  steps:
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v3.0.0
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ inputs.github-token }}

  - name: Fetch multi-platform package version SHAs
    id: multi-arch-digests
    run: |
      package1=$(docker manifest inspect ghcr.io/package1 | jq -r '.manifests.[] | .digest' | paste -s -d ' ' -)
      package2=$(docker manifest inspect ghcr.io/package2 | jq -r '.manifests.[] | .digest' | paste -s -d ' ' -)
      echo "multi-arch-digests=$package1,$package2" >> $GITHUB_OUTPUT
    shell: bash

  - uses: snok/container-retention-policy
    with:
      skip-shas: ${{ steps.multi-arch-digests.outputs.multi-arch-digests }}
