name: 'Build OCI Image (Clean)'
description: 'CLean OCI image.'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  distro:
    description: 'Target distribution (e.g., bookworm, trixie)'
    required: false
  ocipgversion:
    description: 'PostgreSQL version (e.g., pg18)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Login to GitHub Container Registry
      run: echo "${{ inputs.github_token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash

    - name: Fetch multi-platform package version SHAs
      id: multi-arch-digests
      run: |
        export OCIPGVERSION="${{ inputs.ocipgversion }}"
        export PG_VERSION_OCI="${OCIPGVERSION#pg}"
        package1=$(docker manifest inspect ghcr.io/pmpetit/pglinter:1.0.1-${PG_VERSION_OCI}-${{ inputs.distro }} | jq -r '.manifests.[] | .digest' | paste -s -d ' ' -)
        echo "multi-arch-digests=$package1" >> $GITHUB_OUTPUT
      shell: bash

    - uses: snok/container-retention-policy@v3.0.1
      with:
        account: user
        token: ${{ inputs.github-token }}
        skip-shas: ${{ steps.multi-arch-digests.outputs.multi-arch-digests }}
