name: 'Build OCI Image (Make)'
description: 'Builds OCI image using make oci_image_amd64 or oci_image_arm64 depending on arch.'
inputs:
  arch:
    description: 'Target architecture (amd64 or arm64)'
    required: true
  distro:
    description: 'Target distribution (e.g., bookworm, trixie)'
    required: false
  ocipgversion:
    description: 'PostgreSQL version (e.g., pg18)'
    required: false
  github-token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - name: CLeanup OCI image for ${{ inputs.arch }}
      run: |
        make oci_test_cleanup
      shell: bash
