---
name: Check Pull Request Title Format

# Use this trigger when you want to use this reusable workflow in your own repository.
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

# on:
#   workflow_call:
#     inputs:
#       requireScope:
#         required: false
#         type: boolean
#         default: false
#         description: Require a scope in the PR title
#       scopes:
#         required: false
#         type: string
#         default: |
#           .*
#         description: By default all scopes are allowed. You can specify a list of scopes separated by a new line.
#       validate_pr_title_fake_caller_job_name:
#         required: false
#         type: string
#         default: Validate PR title
#         description: |
#           Name of the caller job so that we can fake the name of the required check
#       subjectPattern:
#         required: false
#         type: string
#         description: By default all subjects are allowed. You can specify a regex pattern to match a specific string in the subject (such as a Jira reference).

permissions:
  # Need to be able to read the PR title and write a comment
  pull-requests: write
  statuses: write

jobs:
  main:
    if: github.event_name != 'merge_group'
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure if the scope is required in the PR title
          requireScope: ${{ inputs.requireScope }}
          scopes: ${{ inputs.scopes }}
          # Add a specific pattern to match a string in the subject
          subjectPattern: ${{ inputs.subjectPattern }}

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey dear contributors ! 👋🏼
            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.
            Error details:
            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true

  merge_group_workaround:
    if: github.event_name == 'merge_group'
    name: Validate PR title
    runs-on: decathlon
    steps:
      - name: Fake 'Validate PR title' check in a merge group
        uses: guibranco/github-status-action-v2@v1.1.13
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          state: success
          description: Real validation skipped because of merge group
          context: ${{ inputs.validate_pr_title_fake_caller_job_name }} / Validate PR title
          sha: ${{ github.sha }}
          target_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
