name: 'Test OCI Image'
description: 'Tests OCI image using make oci_test depending on arch.'
inputs:
  distro:
    description: 'Target distribution (e.g., bookworm, trixie)'
    required: false
  ocipgversion:
    description: 'PostgreSQL version (e.g., pg18)'
    required: false
  github-token:
    description: 'GitHub token for authentication'
    required: true
  oci-tag:
    description: 'image tag'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Login to GitHub Container Registry
      run: echo "${{ inputs.github_token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash
    - name: Test OCI image
      run: |
        export DISTRO="${{ inputs.distro || 'bookworm' }}"
        export OCIPGVERSION="${{ inputs.ocipgversion }}"
        export PG_VERSION_OCI="${OCIPGVERSION#pg}"
        if [ -n "${{ inputs.oci-tag }}" ]; then
          export OCI_TAG="${{ inputs.oci-tag }}"
        fi
        sudo make oci_test
      shell: bash
    - name: Cleanup OCI image
      run: |
        sudo make oci_test_cleanup
      shell: bash
