name: 'Test OCI Image'
description: 'Tests OCI image using make oci_test depending on arch.'
inputs:
  distro:
    description: 'Target distribution (e.g., bookworm, trixie)'
    required: false
  ocipgversion:
    description: 'PostgreSQL version (e.g., pg18)'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Test OCI image
      run: |
        export DISTRO="${{ inputs.distro || 'bookworm' }}"
        export OCIPGVERSION="${{ inputs.ocipgversion }}"
        export PG_VERSION_OCI="${OCIPGVERSION#pg}"
        make oci_test
      shell: bash
