name: "Test OCI Image"
description: "Tests OCI image using make oci_test depending on arch."
inputs:
  distro:
    description: "Target distribution (e.g., bookworm, trixie)"
    required: false
  ocipgversion:
    description: "PostgreSQL version (e.g., pg18)"
    required: false
  github-token:
    description: "GitHub token for authentication"
    required: true
  oci-tag:
    description: "image tag"
    required: false
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      run: echo "${{ inputs.github_token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash
    - name: Test OCI image
      run: |
        export DISTRO="${{ inputs.distro || 'bookworm' }}"
        export OCIPGVERSION="${{ inputs.ocipgversion }}"
        export PG_VERSION_OCI="${OCIPGVERSION#pg}"
        if [ -n "${{ inputs.oci-tag }}" ]; then
          export OCI_TAG="${{ inputs.oci-tag }}"
        fi
        # Detect architecture and run appropriate make target
        ARCH=$(uname -m)
        if [ "$ARCH" = "x86_64" ]; then
          sudo make oci_test_amd64
        elif [ "$ARCH" = "aarch64" ] || [ "$ARCH" = "arm64" ]; then
          sudo make oci_test_arm64
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi
      shell: bash
    - name: Cleanup OCI image
      run: |
        sudo make oci_test_cleanup
      shell: bash
