name: 'Install PostgreSQL'
description: 'Installs PostgreSQL from PGDG repository on Ubuntu'

inputs:
  pgver:
    description: 'PostgreSQL version (e.g., pg17)'
    required: true
  package_type:
    description: 'Package type being tested (deb or rpm)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        if [ "${{ inputs.package_type }}" = "rpm" ]; then
          sudo apt-get install -y wget ca-certificates lsb-release rpm alien
        else
          sudo apt-get install -y wget ca-certificates lsb-release
        fi
      shell: bash

    - name: Add PGDG repository
      run: |
        # Add PGDG repository
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
        sudo apt-get update
      shell: bash

    - name: Install PostgreSQL
      run: |
        # Extract PG version number
        PG_VERSION=$(echo "${{ inputs.pgver }}" | sed 's/pg//')
        echo "Installing PostgreSQL version: $PG_VERSION"

        sudo apt-get install -y postgresql-${PG_VERSION} postgresql-client-${PG_VERSION} postgresql-contrib-${PG_VERSION}

        # Start PostgreSQL
        sudo systemctl start postgresql
        sudo systemctl enable postgresql

        # Verify PostgreSQL is running
        sudo systemctl status postgresql --no-pager

        echo "PostgreSQL $PG_VERSION installation completed"
      shell: bash
