name: 'Build OCI Extension Image'
description: 'Build and optionally push CloudNative-PG compatible OCI extension image for pglinter'

inputs:
  postgresql-version:
    description: 'PostgreSQL major version (e.g., 18)'
    required: true
    default: '18'

  distro:
    description: 'Linux distribution (e.g., bookworm)'
    required: true
    default: 'bookworm'

  registry:
    description: 'Container registry (e.g., ghcr.io/pmpetit)'
    required: true
    default: 'ghcr.io/pmpetit'

  image-name:
    description: 'Image name (e.g., pglinter)'
    required: true
    default: 'pglinter'

  push:
    description: 'Whether to push the image to registry'
    required: false
    default: 'false'

  platforms:
    description: 'Target platforms for multi-arch build'
    required: false
    default: 'linux/amd64,linux/arm64'

  build-local:
    description: 'Use local .deb packages instead of downloading from releases'
    required: false
    default: 'false'

outputs:
  image-tags:
    description: 'Generated image tags'
    value: ${{ steps.build.outputs.image-tags }}

  image-digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host

    - name: Build .deb package using pgrx image
      if: inputs.build-local == 'true'
      shell: bash
      run: |
        echo "Building .deb package using pgrx image: ghcr.io/pmpetit/postgresql_pglinter:pgrx"

        # Create output directory for packages
        mkdir -p ./target/release/pglinter-pg${{ inputs.postgresql-version }}/

        # Run the build in the pgrx container
        docker run --rm \
          --volume "$(pwd):/pgrx" \
          --workdir /pgrx \
          --user $(id -u):$(id -g) \
          ghcr.io/pmpetit/postgresql_pglinter:pgrx \
          bash -c "
            echo 'Building pglinter extension...' &&
            make deb PGVER=pg${{ inputs.postgresql-version }} PG_MAJOR_VERSION=${{ inputs.postgresql-version }} &&
            echo 'Package build completed.' &&
            ls -la target/release/pglinter-pg${{ inputs.postgresql-version }}/ || echo 'No packages found'
          "

        # Verify the package was built
        if [ ! -f target/release/pglinter-pg${{ inputs.postgresql-version }}/postgresql_pglinter_${{ inputs.postgresql-version }}_*.deb ]; then
          echo "❌ .deb package not found after build"
          exit 1
        fi

        echo "✅ .deb package built successfully"
        ls -la target/release/pglinter-pg${{ inputs.postgresql-version }}/

    - name: Prepare build context
      shell: bash
      run: |
        # Generate timestamp for tagging
        echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

        # Extract version from Cargo.toml
        PGLINTER_VERSION=$(grep '^version *= *' Cargo.toml | sed 's/^version *= *//' | tr -d '"' | tr -d ' ')
        echo "PGLINTER_VERSION=$PGLINTER_VERSION" >> $GITHUB_ENV

        # Set image tags
        BASE_TAG="$PGLINTER_VERSION"
        FULL_TAG="$PGLINTER_VERSION-$(date +%Y%m%d%H%M%S)-pg${{ inputs.postgresql-version }}-${{ inputs.distro }}"

        echo "BASE_TAG=$BASE_TAG" >> $GITHUB_ENV
        echo "FULL_TAG=$FULL_TAG" >> $GITHUB_ENV

        # Determine Dockerfile to use
        if [[ "${{ inputs.build-local }}" == "true" ]]; then
          # For local builds, prepare .deb package
          mkdir -p docker/oci/packages
          cp target/release/pglinter-pg${{ inputs.postgresql-version }}/postgresql_pglinter_${{ inputs.postgresql-version }}_${PGLINTER_VERSION}_amd64.deb docker/oci/packages/pglinter.deb
          echo "DOCKERFILE=docker/oci/Dockerfile.local" >> $GITHUB_ENV
          echo "BUILD_CONTEXT=docker/oci" >> $GITHUB_ENV
        else
          # For release builds, use GitHub releases
          echo "DOCKERFILE=docker/oci/Dockerfile" >> $GITHUB_ENV
          echo "BUILD_CONTEXT=." >> $GITHUB_ENV
        fi

    - name: Build and push OCI image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.BUILD_CONTEXT }}
        file: ${{ env.DOCKERFILE }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        build-args: |
          PG_VERSION=${{ inputs.postgresql-version }}
          DISTRO=${{ inputs.distro }}
          PGLINTER_VERSION=${{ env.PGLINTER_VERSION }}
          TIMESTAMP=${{ env.TIMESTAMP }}
          EXT_VERSION=${{ env.PGLINTER_VERSION }}
        tags: |
          ${{ inputs.registry }}/${{ inputs.image-name }}:${{ env.FULL_TAG }}
          ${{ inputs.registry }}/${{ inputs.image-name }}:latest
          ${{ inputs.registry }}/${{ inputs.image-name }}:${{ env.BASE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Output image information
      shell: bash
      run: |
        echo "image-tags=${{ inputs.registry }}/${{ inputs.image-name }}:${{ env.FULL_TAG }},${{ inputs.registry }}/${{ inputs.image-name }}:latest,${{ inputs.registry }}/${{ inputs.image-name }}:${{ env.BASE_TAG }}" >> $GITHUB_OUTPUT
        echo "Built OCI image with tags:"
        echo "  - ${{ inputs.registry }}/${{ inputs.image-name }}:${{ env.FULL_TAG }}"
        echo "  - ${{ inputs.registry }}/${{ inputs.image-name }}:latest"
        echo "  - ${{ inputs.registry }}/${{ inputs.image-name }}:${{ env.BASE_TAG }}"

    - name: Clean up build context
      if: always() && inputs.build-local == 'true'
      shell: bash
      run: |
        rm -rf docker/oci/packages || true
