name: 'Mark Release Production Ready'
description: 'Marks a GitHub release as production ready (removes prerelease flag) for a given tag.'

inputs:
  github_token:
    description: 'GitHub token with repo access'
    required: true
  release_tag:
    description: 'Tag name of the release to update'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install gh CLI
      run: |
        if ! command -v gh &> /dev/null; then
          echo "Installing GitHub CLI..."
          sudo apt-get update && sudo apt-get install -y gh
        fi
      shell: bash

    - name: Mark release as production ready
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        RELEASE_TAG: ${{ inputs.release_tag }}
      run: |
        echo "Looking for release with tag: $RELEASE_TAG"
        RELEASE_ID=$(gh api repos/${{ github.repository }}/releases --jq ".[] | select(.tag_name==\"$RELEASE_TAG\") | .id")
        if [ -n "$RELEASE_ID" ]; then
          echo "Updating release $RELEASE_ID to production ready"
          gh api --method PATCH repos/${{ github.repository }}/releases/$RELEASE_ID \
            -f prerelease=false
        else
          echo "No release found for tag $RELEASE_TAG"
        fi
      shell: bash
