name: 'Create GitHub Release'

description: 'Downloads artifacts and creates a GitHub release with all packages'

inputs:
  tag:
    description: 'The tag/version for the release'
    required: true
  github-token:
    description: 'GitHub token for creating releases'
    required: true
  prerelease:
    description: 'Mark as prerelease'
    required: false
    default: 'false'
  draft:
    description: 'Create as draft'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        merge-multiple: true

    - name: Display downloaded artifacts
      run: |
        echo "Downloaded artifacts:"
        find ./artifacts -name "*.rpm" -o -name "*.deb" | sort
        echo ""
        echo "Artifact count:"
        find ./artifacts -name "*.rpm" -o -name "*.deb" | wc -l
      shell: bash

    - name: Validate artifacts
      run: |
        rpm_count=$(find ./artifacts -name "*.rpm" | wc -l)
        deb_count=$(find ./artifacts -name "*.deb" | wc -l)

        echo "Found $rpm_count RPM packages"
        echo "Found $deb_count DEB packages"

        if [ "$rpm_count" -eq 0 ] && [ "$deb_count" -eq 0 ]; then
          echo "ERROR: No packages found to release!"
          exit 1
        fi
      shell: bash

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        tag_name: ${{ inputs.tag }}
        name: pglinter v${{ inputs.tag }}
        draft: ${{ inputs.draft }}
        prerelease: ${{ inputs.prerelease }}
        files: |
          ./artifacts/*.rpm
          ./artifacts/*.deb

    - name: List release assets
      run: |
        echo "Release created successfully!"
        echo "Release URL: ${{ steps.create_release.outputs.url }}"
        echo ""
        echo "Uploaded files:"
        find ./artifacts \( -name "*.rpm" -o -name "*.deb" \) -exec basename {} \; | sort
      shell: bash
