# Main workflow that uses the reusable build_and_test_pgver workflow
# Similar to how GitLab CI would include the template

name: 'Build and Test All PostgreSQL Versions'

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * 0'  # Weekly on Sunday at 2 AM
  workflow_dispatch:

jobs:
  # Build and test PostgreSQL 13 (with always flag)
  pg13:
    uses: ./.github/workflows/build_and_test_pgver.yml
    with:
      pgver: 'pg13'
      always: 'true'  # Always run for pg13

  # Build and test PostgreSQL 14
  pg14:
    uses: ./.github/workflows/build_and_test_pgver.yml
    with:
      pgver: 'pg14'

  # Build and test PostgreSQL 15
  pg15:
    uses: ./.github/workflows/build_and_test_pgver.yml
    with:
      pgver: 'pg15'

  # Build and test PostgreSQL 16
  pg16:
    uses: ./.github/workflows/build_and_test_pgver.yml
    with:
      pgver: 'pg16'

  # Build and test PostgreSQL 17
  pg17:
    uses: ./.github/workflows/build_and_test_pgver.yml
    with:
      pgver: 'pg17'
