# Example of how to use the composite action
name: 'Example Usage of PR Title Action'

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: ./.github/actions/check_title
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          requireScope: false
