# .github/workflows/main.yml
name: 'MAIN Build and Test PostgreSQL Version'

on:
  workflow_call:
    inputs:
      always:
        description: 'If defined, all jobs are launched in any case. Usually you want at least 1 major version to be built/tested on all pipelines.'
        type: string
        default: ''
        required: false
      pgver:
        description: 'The PostgreSQL major version with the "pg" prefix (e.g. `pg13`, `pg16`, etc.)'
        type: string
        required: true
  workflow_dispatch:
    inputs:
      pgver:
        description: 'PostgreSQL version with pg prefix (e.g., pg13, pg16)'
        required: true
        default: 'pg16'
        type: string

env:
  PGVER: ${{ inputs.pgver }}
  ALWAYS: ${{ inputs.always }}

jobs:
  build:
    name: 'build-${{ inputs.pgver }}'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pmpetit/postgresql_pglinter:pgrx
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    if: |
      inputs.always != '' ||
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      github.ref == github.event.repository.default_branch ||
      startsWith(github.ref, 'refs/tags/')

    steps:
      - name: 'Call reusable build action'
        uses: ./.github/actions/reusable-build-action
        with:
          pgver: ${{ inputs.pgver }}
          always: ${{ inputs.always }}
