
name: 'Build and Test PostgreSQL Version'

on:
  pull_request:
    branches:
      - main  # Optional: specify branches for the pull request to merge into
  workflow_dispatch:
    #inputs:
      # pgver:
      #   description: 'PostgreSQL version with pg prefix (e.g., pg13, pg16)'
      #   required: true
      #   default: 'pg16'
      #   type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  ##
  ## B U I L D / T E S T
  ##
  build:
    strategy:
      matrix:
        pgver: [13]
      fail-fast: false
    name: 'build-test-pg${{ matrix.pgver }}'
    runs-on: ubuntu-latest
    # Use GitHub Container Registry for pmpetit
    container:
      image: ghcr.io/pmpetit/postgresql_pglinter:pgrx
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Call reusable build action
        uses: ./.github/actions/reusable-build-action
        with:
          pgver: ${{ matrix.pgver }}
          always: ${{ matrix.pgver == 'pg13' && 'yes' || '' }}
