# as main is protected, you can't commit into without a PR.
# So in main only validated PR are accepted.
# So build and test were run during the merge request process.
# So don't need to run twice the build and test workflow when releasing...
#
# Note: PGXN publishing is handled by a separate workflow (pgxn-publish.yml)
# which automatically triggers when a release is published.

name: 'Package and deploy pglinter.'

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'README.md'
      - 'mkdocs.yml'

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.0.17)'
        required: true
        type: string
      pgversions:
        description: 'PostgreSQL versions to build (comma-separated: pg13,pg14,pg15,pg16,pg17,pg18)'
        required: false
        default: 'pg17'
        type: string


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  ##
  ## D Y N A M I C   M A T R I X   G E N E R A T I O N
  ##
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      pgversions: ${{ steps.matrix.outputs.pgversions }}
    steps:
      - name: Generate matrix
        id: matrix
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            PGVERSIONS="${{ inputs.pgversions }}"
            echo "Using workflow_dispatch pgversions: $PGVERSIONS"
          else
            PGVERSIONS="pg13,pg14,pg15,pg16,pg17,pg18"
            echo "Using default pgversions: $PGVERSIONS"
          fi

          # Create JSON array by replacing commas and wrapping
          JSON_ARRAY=$(echo "[$PGVERSIONS]" | sed 's/,/","/g' | sed 's/\[/["/' | sed 's/\]/"]/')

          echo "Generated matrix: $JSON_ARRAY"
          echo "pgversions=$JSON_ARRAY" >> $GITHUB_OUTPUT

  ##
  ## A M D 6 4   B U I L D S   ( U S I N G   C O N T A I N E R )
  ##
  build-amd64:
    needs: setup-matrix
    strategy:
      matrix:
        pgver: ${{ fromJSON(needs.setup-matrix.outputs.pgversions) }}
      fail-fast: false
    name: 'package-and-deploy-pglinter-for-${{ matrix.pgver }}'
    runs-on: ubuntu-latest
    # Use GitHub Container Registry for pmpetit
    container:
      image: ghcr.io/pmpetit/postgresql_pglinter:pgrx-amd64
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: create deb package
        uses: ./.github/actions/reusable-package-action
        with:
          pgver: ${{ matrix.pgver }}
          tag: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}
          arch: amd64

  test-deb-amd64-package:
    needs: [build-amd64,setup-matrix]
    strategy:
      matrix:
        pgver: ${{ fromJSON(needs.setup-matrix.outputs.pgversions) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract major version
        id: extract_pgver
        run: echo "PG_VERSION=${{ matrix.pgver:2 }}" >> $GITHUB_OUTPUT
      - name: Download deb package
        uses: actions/download-artifact@v4
        with:
          name: pglinter-${{ matrix.pgver }}-${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}-amd64.deb
          path: ./artifacts
      - name: Test deb package
        uses: ./.github/actions/reusable-test-deb-package
        with:
          pg_version:  ${{ steps.extract_pgver.outputs.PG_VERSION }}
          pglinter_version: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}
          platform: 'linux/amd64'
          timeout: '180'

  #
  # A R M 6 4   B U I L D S   ( D I R E C T   I N S T A L L A T I O N )
  #
  build-arm64:
    needs: setup-matrix
    strategy:
      matrix:
        pgver: ${{ fromJSON(needs.setup-matrix.outputs.pgversions) }}
      fail-fast: false
    name: 'package-and-deploy-pglinter-for-${{ matrix.pgver }}'
    runs-on: ubuntu-24.04-arm
    # Use GitHub Container Registry for pmpetit
    container:
      image: ghcr.io/pmpetit/postgresql_pglinter:pgrx-arm64
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Call reusable package action
        uses: ./.github/actions/reusable-package-action
        with:
          pgver: ${{ matrix.pgver }}
          tag: ${{ github.ref_name }}
          arch: arm64
          pkgtype: deb

  test-deb-arm64-package:
    needs: [build-arm64,setup-matrix]
    strategy:
      matrix:
        pgver: ${{ fromJSON(needs.setup-matrix.outputs.pgversions) }}
      fail-fast: false
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract major version
        id: extract_pgver
        run: echo "PG_VERSION=${{ matrix.pgver:2 }}" >> $GITHUB_OUTPUT
      - name: Download deb package
        uses: actions/download-artifact@v4
        with:
          name: pglinter-${{ matrix.pgver }}-${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}-arm64.deb
          path: ./artifacts
      - name: Test deb package
        uses: ./.github/actions/reusable-test-deb-package
        with:
          pg_version:  ${{ steps.extract_pgver.outputs.PG_VERSION }}
          pglinter_version: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}
          platform: 'linux/arm64'
          timeout: '180'

  # create-release:
  #   needs: [build-amd64]
  #   runs-on: ubuntu-latest
  #   if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'

  #   permissions:
  #     contents: write
  #     packages: read

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Create Release Action
  #       if: success()
  #       uses: ./.github/actions/reusable-release-action
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         release_tag: ${{ input.version }}
