name: Test PostgreSQL NODEB Package

on:
  workflow_dispatch:
    inputs:
      pg_version:
        description: 'PostgreSQL version to test'
        required: true
        default: '17'
        type: choice
        options: ['13', '14', '15', '16', '17', '18']
      pglinter_version:
        description: 'pglinter version'
        required: true
        default: '0.0.19'
      platform:
        description: 'Target platform'
        required: false
        default: 'linux/amd64'
      timeout:
        description: 'Container timeout (seconds)'
        required: false
        default: '120'

jobs:
  test-nodeb-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test PostgreSQL NODEB image
        uses: ./.github/actions/reusable-test-nodeb-package
        with:
          pg_version: ${{ inputs.pg_version }}
          pglinter_version: ${{ inputs.pglinter_version }}
          platform: ${{ inputs.platform }}
          timeout: ${{ inputs.timeout }}
